### PR TITLE
Update msg.md

### PR DESCRIPTION
**Pull request by clinique**
Typo in Message topic

### CODE REVIEW

**Comment by jpmens** [comment]
That is _not_ a typo; it is `msg`.

**Comment by clinique** [comment]
Unfortunately not, currently the android app doesn't react to 
owntracks/user/device/msg
but only to 
owntracks/user/device/cmd

**Comment by jpmens** [comment]
What do you mean by 'react to'? `cmd` is for sending commands to it, which `msg` is for messaging. Have you looked at [Messages](http://owntracks.org/booklet/features/msg/) ?

**Comment by clinique** [comment]
I mean that no message is received on the android app with the topic as described in the documentation. Instead, it works with /cmd. Found that after unsuccessfull trials and looked into code : 

In ServiceBroker.java #442 :  
if (Preferences.getDirectMessageEnable() && !Preferences.isModePublic())
                topics.add(subTopicBase + Preferences.getPubTopicCommandsPart()); 

and in Preferences.java #595 : 
    public static String getPubTopicCommandsPart() {
        return "/cmd";
    }

**Comment by jpmens** [comment]
Please do us a favor then, and open an issue for our Android app at github.com/owntracks/android and basically copy this into that? That'd be a great help, thanks.

**Comment by clinique** [comment]
Ok, done

**Comment by jpmens** [comment]
Thank you.
(continued in https://github.com/owntracks/android/issues/294)

**Pull request closed without merging**
